commands = [
"?  Show commands",
"h  Move left",
"j  Move down",
"k  Move up",
"l  Move right",
"i  See inventory",
"e  Eat some food",
"Q  Quit game",
"w  Equip weapon",
"W  Equip armor",
">  Go down a staircase",
"p  Drink potion",
"r  Read scroll",
"d  Drop item"]
